// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: cat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListKittsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// if id is empty, then kitts will be returned from the beginning
	CatId int32 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
}

func (x *ListKittsRequest) Reset() {
	*x = ListKittsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKittsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKittsRequest) ProtoMessage() {}

func (x *ListKittsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKittsRequest.ProtoReflect.Descriptor instead.
func (*ListKittsRequest) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{0}
}

func (x *ListKittsRequest) GetCatId() int32 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type ListKittsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kitts []*GetKittResponse `protobuf:"bytes,1,rep,name=kitts,proto3" json:"kitts,omitempty"`
}

func (x *ListKittsResponse) Reset() {
	*x = ListKittsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKittsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKittsResponse) ProtoMessage() {}

func (x *ListKittsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKittsResponse.ProtoReflect.Descriptor instead.
func (*ListKittsResponse) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{1}
}

func (x *ListKittsResponse) GetKitts() []*GetKittResponse {
	if x != nil {
		return x.Kitts
	}
	return nil
}

type CreateKittRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	CatId   int32  `protobuf:"varint,2,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
}

func (x *CreateKittRequest) Reset() {
	*x = CreateKittRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKittRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKittRequest) ProtoMessage() {}

func (x *CreateKittRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKittRequest.ProtoReflect.Descriptor instead.
func (*CreateKittRequest) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKittRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateKittRequest) GetCatId() int32 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type CreateKittResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateKittResponse) Reset() {
	*x = CreateKittResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateKittResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKittResponse) ProtoMessage() {}

func (x *CreateKittResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKittResponse.ProtoReflect.Descriptor instead.
func (*CreateKittResponse) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{3}
}

func (x *CreateKittResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetKittRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetKittRequest) Reset() {
	*x = GetKittRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKittRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKittRequest) ProtoMessage() {}

func (x *GetKittRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKittRequest.ProtoReflect.Descriptor instead.
func (*GetKittRequest) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{4}
}

func (x *GetKittRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetKittResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content   string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CatId     int32  `protobuf:"varint,4,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
}

func (x *GetKittResponse) Reset() {
	*x = GetKittResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKittResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKittResponse) ProtoMessage() {}

func (x *GetKittResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKittResponse.ProtoReflect.Descriptor instead.
func (*GetKittResponse) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{5}
}

func (x *GetKittResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetKittResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetKittResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetKittResponse) GetCatId() int32 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type LoginCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginCatRequest) Reset() {
	*x = LoginCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCatRequest) ProtoMessage() {}

func (x *LoginCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCatRequest.ProtoReflect.Descriptor instead.
func (*LoginCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{6}
}

func (x *LoginCatRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginCatRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginCatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *LoginCatResponse) Reset() {
	*x = LoginCatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCatResponse) ProtoMessage() {}

func (x *LoginCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginCatResponse.ProtoReflect.Descriptor instead.
func (*LoginCatResponse) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{7}
}

func (x *LoginCatResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetCatRequest is data for getting a cat
type GetCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is an id of a cat
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCatRequest) Reset() {
	*x = GetCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatRequest) ProtoMessage() {}

func (x *GetCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatRequest.ProtoReflect.Descriptor instead.
func (*GetCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{8}
}

func (x *GetCatRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetCatResponse is answer of service during getting a cat
type GetCatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is an id of a cat, it is unique
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is a name of a cat
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// usename is unchangable username of a cat
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// bio is optional description of a cat
	Bio *string `protobuf:"bytes,4,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
}

func (x *GetCatResponse) Reset() {
	*x = GetCatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatResponse) ProtoMessage() {}

func (x *GetCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatResponse.ProtoReflect.Descriptor instead.
func (*GetCatResponse) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{9}
}

func (x *GetCatResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCatResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCatResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetCatResponse) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

// RegisterCatRequest is data for creating a cat
type RegisterCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is a name of a cat
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// usename is unchangable username of a cat
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// bio is optional description of a cat
	Bio      *string `protobuf:"bytes,3,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	Password string  `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RegisterCatRequest) Reset() {
	*x = RegisterCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCatRequest) ProtoMessage() {}

func (x *RegisterCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCatRequest.ProtoReflect.Descriptor instead.
func (*RegisterCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterCatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterCatRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterCatRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *RegisterCatRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegisterCatResponse is answer of service during creating a cat
type RegisterCatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is an id of a cat, it is unique
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegisterCatResponse) Reset() {
	*x = RegisterCatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCatResponse) ProtoMessage() {}

func (x *RegisterCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCatResponse.ProtoReflect.Descriptor instead.
func (*RegisterCatResponse) Descriptor() ([]byte, []int) {
	return file_cat_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterCatResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_cat_proto protoreflect.FileDescriptor

var file_cat_proto_rawDesc = []byte{
	0x0a, 0x09, 0x63, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x22, 0x29, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x69, 0x74, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x4b, 0x69, 0x74, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2b, 0x0a, 0x05, 0x6b, 0x69, 0x74, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x74, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x6b, 0x69, 0x74, 0x74, 0x73, 0x22, 0x44,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x74, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x63, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x61, 0x74, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69,
	0x74, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x4b, 0x69, 0x74, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x4b, 0x69, 0x74, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x61, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x22,
	0x49, 0x0a, 0x0f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1f,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x6f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x15, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x03, 0x62, 0x69, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x62, 0x69, 0x6f,
	0x22, 0x7f, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x62, 0x69, 0x6f, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x62, 0x69,
	0x6f, 0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0xed, 0x02, 0x0a, 0x06, 0x43, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x18, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43,
	0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x70, 0x65, 0x63,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x15, 0x2e,
	0x73, 0x70, 0x65, 0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x06,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x12, 0x13, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x70,
	0x65, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x74, 0x74, 0x12,
	0x17, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x74,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4b, 0x69, 0x74, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x74, 0x74, 0x12, 0x14, 0x2e,
	0x73, 0x70, 0x65, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69, 0x74, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x69,
	0x74, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x4c, 0x69,
	0x73, 0x74, 0x4b, 0x69, 0x74, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4b, 0x69, 0x74, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x69, 0x74, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cat_proto_rawDescOnce sync.Once
	file_cat_proto_rawDescData = file_cat_proto_rawDesc
)

func file_cat_proto_rawDescGZIP() []byte {
	file_cat_proto_rawDescOnce.Do(func() {
		file_cat_proto_rawDescData = protoimpl.X.CompressGZIP(file_cat_proto_rawDescData)
	})
	return file_cat_proto_rawDescData
}

var file_cat_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cat_proto_goTypes = []interface{}{
	(*ListKittsRequest)(nil),    // 0: spec.ListKittsRequest
	(*ListKittsResponse)(nil),   // 1: spec.ListKittsResponse
	(*CreateKittRequest)(nil),   // 2: spec.CreateKittRequest
	(*CreateKittResponse)(nil),  // 3: spec.CreateKittResponse
	(*GetKittRequest)(nil),      // 4: spec.GetKittRequest
	(*GetKittResponse)(nil),     // 5: spec.GetKittResponse
	(*LoginCatRequest)(nil),     // 6: spec.LoginCatRequest
	(*LoginCatResponse)(nil),    // 7: spec.LoginCatResponse
	(*GetCatRequest)(nil),       // 8: spec.GetCatRequest
	(*GetCatResponse)(nil),      // 9: spec.GetCatResponse
	(*RegisterCatRequest)(nil),  // 10: spec.RegisterCatRequest
	(*RegisterCatResponse)(nil), // 11: spec.RegisterCatResponse
}
var file_cat_proto_depIdxs = []int32{
	5,  // 0: spec.ListKittsResponse.kitts:type_name -> spec.GetKittResponse
	10, // 1: spec.Catter.Register:input_type -> spec.RegisterCatRequest
	6,  // 2: spec.Catter.Login:input_type -> spec.LoginCatRequest
	8,  // 3: spec.Catter.GetCat:input_type -> spec.GetCatRequest
	2,  // 4: spec.Catter.CreateKitt:input_type -> spec.CreateKittRequest
	4,  // 5: spec.Catter.GetKitt:input_type -> spec.GetKittRequest
	0,  // 6: spec.Catter.ListKitts:input_type -> spec.ListKittsRequest
	11, // 7: spec.Catter.Register:output_type -> spec.RegisterCatResponse
	7,  // 8: spec.Catter.Login:output_type -> spec.LoginCatResponse
	9,  // 9: spec.Catter.GetCat:output_type -> spec.GetCatResponse
	3,  // 10: spec.Catter.CreateKitt:output_type -> spec.CreateKittResponse
	5,  // 11: spec.Catter.GetKitt:output_type -> spec.GetKittResponse
	1,  // 12: spec.Catter.ListKitts:output_type -> spec.ListKittsResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_cat_proto_init() }
func file_cat_proto_init() {
	if File_cat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKittsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKittsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKittRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateKittResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKittRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKittResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginCatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterCatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cat_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_cat_proto_msgTypes[10].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cat_proto_goTypes,
		DependencyIndexes: file_cat_proto_depIdxs,
		MessageInfos:      file_cat_proto_msgTypes,
	}.Build()
	File_cat_proto = out.File
	file_cat_proto_rawDesc = nil
	file_cat_proto_goTypes = nil
	file_cat_proto_depIdxs = nil
}
